CREATE DATABASE EMPLOYEE_TABLE

CREATE TABLE EMPLOYEE_TABLE(
    ID INT(10) PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(20),
    CITY VARCHAR(20),
    COUNTRY VARCHAR(20),
    AGE INT(10),
    SALARY INT(10),
    EXPERIENCE INT (10),
    DEPARTMENT VARCHAR(10),
    DESIGNATION VARCHAR(20));

INSERT INTO EMPLOYEE_TABLE(NAME,CITY,COUNTRY,AGE,SALARY,EXPERIENCE,DEPARTMENT,DESIGNATION)
VALUES('JANE','BROOKLYN','USA',25,6000,5,'CSE','LECTURER'),
('JACK','LONDON','ENGLAND',32,5000,7,'EEE','AP'),
('PENNY','YALE','CANADA',26,6000,5,'ETE','AP'),
('PAIGE','NEVADA','USA',32,3000,8,'CSE','PROF'),
('MISSY','BROOKLYN','USA',25,3000,6,'CSE','LECTURER'),
('LINDA','TORONTO','CANDA',26,4000,3,'EEE','AP'),
('LINDA','YORK','CANADA',24,3000,4,'CSE','AP'),
('MISSY','BERLIN','GERMANY',24,4000,5,'ETE','AP'),
('PAIGE','HUMBARG','GERMANY',32,6000,6,'ETE','AP'),
 ('MISSY','BERLIN','GERMANY',40,9000,9,'CSE','PROF');

SELECT DISTINCT COUNTRY FROM EMPLOYEE_TABLE;

SELECT DISTINCT COUNTRY AS 'HISHAM' FROM EMPLOYEE_TABLE

SELECT DISTINCT CITY AS 'HISHAM' FROM EMPLOYEE_TABLE

SELECT MAX(SALARY) AS MAX_SALARY FROM EMPLOYEE_TABLE;
SELECT MIN(SALARY) AS MIN_SALARY FROM EMPLOYEE_TABLE;
SELECT AVG(SALARY) AS AVG_SALARY FROM EMPLOYEE_TABLE;
SELECT SUM(SALARY) AS SUM_SALARY FROM EMPLOYEE_TABLE;
SELECT COUNT(SALARY) AS COUNT_SALARY FROM EMPLOYEE_TABLE;

SELECT MAX(SALARY) AS 'MAX_SALARY',MIN(SALARY)'MIN_SALARY' FROM EMPLOYEE_TABLE;

SELECT COUNT(DISTINCT NAME),COUNT(DISTINCT CITY),COUNT(DISTINCT COUNTRY)FROM EMPLOYEE_TABLE;

SELECT UCASE(NAME)AS 'UPPER_NAME',LCASE(NAME) AS 'LOWER_CASE' FROM EMPLOYEE_TABLE;
SELECT MID(NAME,1,2)FROM EMPLOYEE_TABLE;

  SELECT NAME FROM EMPLOYEE_TABLE WHERE CITY IN ('BROOKLYN','BERLIN','HUMBARG');
 SELECT NAME FROM EMPLOYEE_TABLE WHERE AGE IN (SELECT MIN(AGE) FROM EMPLOYEE_TABLE);

